platform :ios, '13.0'

def flutter_install_all_ios_pods(flutter_application_path = nil)
  flutter_application_path ||= File.expand_path('..', __dir__)
  load File.join(flutter_application_path, '.ios', 'podhelper.rb')
end

def flutter_install_ios_engine_pod(flutter_application_path)
  engine_dir = File.expand_path(File.join(flutter_application_path, 'engine'))
  framework_dir = File.expand_path(File.join(engine_dir, 'Flutter.xcframework'))

  puts "Engine directory: #{engine_dir}"
  puts "Framework directory: #{framework_dir}"

  pod 'Flutter', :path => framework_dir
end

def flutter_install_ios_plugin_pods(flutter_application_path)
  flutter_application_path ||= File.expand_path('..', __dir__)
  load File.join(flutter_application_path, '.ios', 'podhelper.rb')
end

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  puts "Generated Xcode build settings path: #{generated_xcode_build_settings_path}" # 경로 출력


  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Pods for Runner
  pod 'Firebase/Core', '10.29.0'
  pod 'Firebase/Auth', '10.29.0'
  pod 'Firebase/Analytics', '10.29.0'
  # pod 'FirebaseAppDistribution', '2.0'
  pod 'GoogleDataTransport'

  pod 'FirebaseFirestore',
    :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git',
    :tag => '10.29.0'

  flutter_install_ios_engine_pod File.dirname(File.realpath(__FILE__))
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end

  installer.pods_project.targets.each do |target|
    if target.name == 'Runner'
      flutter_xcframework_path = File.expand_path(File.join('..', 'engine', 'Flutter.xcframework'), __dir__)
      target.build_configurations.each do |config|
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= '$(inherited)'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << " #{flutter_xcframework_path}"
      end
    end
  end

end
